name: Python test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dbus libdbus-1-dev
      - name: Verify changes
        uses: EffectiveRange/python-verify-github-action@v1
        with:
          coverage-threshold: '95'
